### ISSUE TITLE
按钮排列成为一列,显示不正常

### ISSUE THREAD

**Issue by iwer8** [rojer95/dslate#1]
![image](https://user-images.githubusercontent.com/29975377/198866261-d0eb8381-c952-415c-ac24-8913eb4b6fb7.png)

**Comment by rojer95** [comment]
可否提供一下复现的代码或者Demo？

**Comment by iwer8** [comment]
> 可否提供一下复现的代码或者Demo？

在您官网提供的codesandbox中的事例就是这样滴: https://codesandbox.io/s/798f03
![image](https://user-images.githubusercontent.com/29975377/199697781-c1b3fac4-e168-4206-9307-0a7cc97f8753.png)

**Comment by rojer95** [comment]
项目的打包方式是bundleless，需要在脚手架引入less-loader同时开启javascriptEnabled哈
