### ISSUE TITLE
如何关闭工具栏上的tooltip提示？

### ISSUE THREAD

**Issue by tigerk** [rojer95/dslate#3]
使用对齐方式时，tooltip挡住了操作按钮，如何关闭掉tooltip？

<img width="1098" alt="截屏2023-02-08 00 21 43" src="https://user-images.githubusercontent.com/11213730/217302445-3a19afbb-4ae4-4a9e-a544-88b08f2e657c.png">

**Comment by rojer95** [comment]
近期我调整一下

**Comment by rojer95** [comment]
已发布 `1.0.11 `

----

`Tooltip` 改为默认展示在上方
同时支持在全局配置方向：

```tsx
<ConfigProvider value={{
    ...defaultConfig,
    pluginProps: {
        tooltip: {
            placement: 'left'
        }
    }
}}>
    <DSlate />
</ConfigProvider>
```
