### ISSUE TITLE
View Mode

### ISSUE THREAD

**Issue by gherciu** [rojer95/dslate#8]
Trying to understand how to use it only to display the value produced by this editor
Something like view mode only
I know there is disabled prop, but htis is quite different it makes teh editor grey and the link still shows the popover (that may be a bug)

**Comment by rojer95** [comment]
You can use the `serialize` method provided by`ref` to convert slate descendant json data to HTML for display
```jsx
 const ref = useRef<DSlateRef>(null);

<DSlate ref={ref} value={value} onChange={setValue} />
<Button
  onClick={() => {
  console.log(
    ref.current?.serialize({
      children: value,
    }),
  );
}}
>
to HTML
</Button>
```

**Comment by gherciu** [comment]
Yes, but that will mean that in DB for example I have to save this as HTML and then to display later
But then if user will want to re-edit I'll need to parse it again

At the moment I save the Array itself in DB since is much more convenient when needed to re-edit

What would be nice to have is a View Component that can display just This array without a toolbar
I think the Editable component from slate has a prop named `readonly` it would be nice if we were able to pass this to the DSlate component so that it becomes readonly and also when hovering on a link In this case it should not display any popup

**Comment by rojer95** [comment]
refer this demo: https://rojer95.github.io/dslate/getting-started/display-mode
